# ----------- CONFIGURABLE START -----------
title:            "サキキのFullStackの道"
subtitle:         ""
description:      "Full Stack Engineer"
baseurl:          
facebook_appid:   
google_analytics: UA-115400557-1

paginate: 8
paginate_path: "/all/page:num/"
plugins: [jekyll-paginate]
links:
  - name:         ホーム
    url:          /
    external:     false
  - name:         全部
    url:          /all
    external:     false
  - name:         タグ
    url:          /tags
    external:     false
  - name:         About
    url:          /about
    external:     false
  - name:         Rss
    url:          /feed.xml
    external:     false

permalink: /:categories/:title.html
defaults:
  - values:
      layout: "default"

markdown: kramdown
highlighter: rouge

disqus:

gitalk:
  clientID: 45d901954f04cc74ce70 #Github Application Client ID
  clientSecret: 1ec7e7946ca50ff0ead500c0fb84736d1777a3ab #Github Application Client Secret
  repository: zamberform.github.io #Github repo
  owner: zamberform #Github repo owner
  admin:  #Github repo owner and collaborators, only these guys can initialize github issues, IT IS A LIST.
    - zamberform

# google_ad_client: 0000000000000000
# google_ad_slot: 00000